require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe CommentsController, :type => :controller do

  it "Status should be 200" do
    comment = FactoryGirl.create(:comment)
    get :index
    response.status.should == 200
  end

  it "renders show template if an iten is found" do
    comment = FactoryGirl.create(:comment)
    get :show, { id: comment.id } 
    response.should render_template('show')
  end

  it "renders 404 page if an item is not found" do
    get :show, { id: 0 }
    response.status.should == 404
  end

  it "redirects to projects" do
    post :create, comment: {text: 'some text and other iteams'}
    response.should redirect_to(assigns(:comment))
  end

  it "renders new page" do
    post :create, comment: {text: nil}
    response.should render_template('new')
  end  

end
