require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ProjectsController, :type => :controller do

  it "renders show template if an item is found" do
    project = FactoryGirl.create(:project)
    get :show, { id: project.id } 
    response.should render_template('show')
  end

  it "renders 404 page if an item is not found" do
    get :show, { id: 0 }
    response.status.should == 404
  end

  it "Status should be 200" do
    project = FactoryGirl.create(:project)
    get :index
    response.status.should == 200
  end

  it "Status should be 203" do
    get :index
    response.status.should == 203
  end

  it "renders index template if an item is found" do
    project = FactoryGirl.create(:project)
    get :index
    response.should render_template('index')
  end

  it "redirects to projects" do
    post :create, project: {name: 'name_project', description: 'some text', date: '14-01-2015'}
    response.should redirect_to(assigns(:project))
  end

  it "renders new page" do
    post :create, project: {name: 'name_project', description: 'some text', date: nil}
    response.should render_template('new')
  end

end
